spring:
  application:
    name: search-updater
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/mydb
#    username: foo
#    password: bar
#    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8090
